wangyu modify the cgi and ap file for wds

diff --git a/rootfs/cgiCommon/etc/ath.dual/apup b/rootfs/cgiCommon/etc/ath.dual/apup
--- a/rootfs/cgiCommon/etc/ath.dual/apup
+++ b/rootfs/cgiCommon/etc/ath.dual/apup
@@ -88,6 +88,9 @@ HOSTAPD_VER=`hostapd -v 2>&1|grep hostapd|cut -f2 -d' '`
 if [ "${BEACON_INT}" = "" ]; then
     BEACON_INT=100
 fi
+if [ "${BEACON_INT_2}" = "" ]; then
+    BEACON_INT_2=400
+fi
 ##
 ## For safety, delete all /tmp nodes we may re-create
 ##
@@ -173,26 +176,97 @@ if [ "${AP_STARTMODE}" = "repeater" -o "${AP_STARTMODE}" = "repeater-ind" ]; the
         APMODE="ap-wds-ind"
         STAMODE="sta-wds-ind"
     fi
+	VAP_NUM=0
     makeVAP ${APMODE} "$AP_SSID" $AP_RADIO_ID:$AP_RFPARAM $BEACON_INT
     if [ $? != 0 ]; then
         echo "Unable to create VAP!"
         exit
     fi
-    makeVAP ${STAMODE} "$AP_SSID_2" $AP_RADIO_ID_2:$AP_RFPARAM_2
+	
+	makeVAP ${APMODE} "$AP_SSID_2" $AP_RADIO_ID_2:$AP_RFPARAM_2 $BEACON_INT
     if [ $? != 0 ]; then
         echo "Unable to create VAP!"
         exit
     fi
-
-    if [ "${AP_SECMODE_2}" != "WPA" -a "${ROOTAP_MAC_2}" != "" ]; then
-        iwconfig ath1 ap $ROOTAP_MAC_2
+	VAP_NUM=$(($VAP_NUM+1))
+    makeVAP ${APMODE} "$AP_SSID_3" $AP_RADIO_ID_3:$AP_RFPARAM_3 $BEACON_INT_2
+    if [ $? != 0 ]; then
+        echo "Unable to create VAP!"
+        exit
     fi
+	VAP_NUM=$(($VAP_NUM+1))
+	
+	makeVAP ${APMODE} "$AP_SSID_4" $AP_RADIO_ID_4:$AP_RFPARAM_4 $BEACON_INT_2
+    if [ $? != 0 ]; then
+        echo "Unable to create VAP!"
+        exit
+    fi
+	VAP_NUM=$(($VAP_NUM+1))
+	wds_flag=`cfg -e | grep  WDSON_OFF= | awk -F'=' '{print $2}'`
+	if [ "${wds_flag}" = "on" ];then
+	if [ "s$STA_SSID" != "s" ];then
+ 	   makeVAP ${STAMODE} "$STA_SSID" $STA_RADIO_ID:$STA_RFPARAM
+	    if [ $? != 0 ]; then
+	        echo "Unable to create VAP!"
+        	exit
+	    fi
+		VAP_NUM=$(($VAP_NUM+1))
+	    if [ "${STA_SECMODE}" != "WPA" -a "${ROOTAP_MAC}" != "" ]; then
+        	iwconfig ath$VAP_NUM ap $ROOTAP_MAC
+	    fi
+	fi
+	fi
+	
+	wds_flag_2=`cfg -e | grep  WDSON_OFF_3= | awk -F'=' '{print $2}'`
+	if [ "${wds_flag_2}" = "on" ];then
+	if [ "s$STA_SSID_2" != "s" ];then
+ 	   makeVAP ${STAMODE} "$STA_SSID_2" $STA_RADIO_ID_2:$STA_RFPARAM_2
+	    if [ $? != 0 ]; then
+	        echo "Unable to create VAP!"
+        	exit
+	    fi
+		VAP_NUM=$(($VAP_NUM+1))
+	    if [ "${STA_SECMODE_2}" != "WPA" -a "${ROOTAP_MAC_2}" != "" ]; then
+        	iwconfig ath$VAP_NUM ap $ROOTAP_MAC_2
+	    fi
+	fi
+	fi
+
+	VAP_NUM=0
+
     if [ "${AP_STARTMODE}" = "repeater-ind" ]; then
         activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
         activateVAP ath1:$AP_RADIO_ID_2 br0 $AP_SECMODE_2 $AP_SECFILE_2 $WPS_ENABLE_2
     else
-        activateVAP ath1:$AP_RADIO_ID_2 br0 $AP_SECMODE_2 $AP_SECFILE_2 $WPS_ENABLE_2
-        activateVAP ath0:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
+        activateVAP ath$VAP_NUM:$AP_RADIO_ID br0 $AP_SECMODE $AP_SECFILE $WPS_ENABLE
+	VAP_NUM=$(($VAP_NUM+1))
+        activateVAP ath$VAP_NUM:$AP_RADIO_ID_2 br0 $AP_SECMODE_2 $AP_SECFILE_2 $WPS_ENABLE_2
+	VAP_NUM=$(($VAP_NUM+1))	
+        activateVAP ath$VAP_NUM:$AP_RADIO_ID_3 br0 $AP_SECMODE_3 $AP_SECFILE_3 $WPS_ENABLE_3
+	VAP_NUM=$(($VAP_NUM+1))
+        activateVAP ath$VAP_NUM:$AP_RADIO_ID_4 br0 $AP_SECMODE_4 $AP_SECFILE_4 $WPS_ENABLE_4
+	VAP_NUM=$(($VAP_NUM+1))	
+	
+	if [ "${wds_flag}" = "on" ];then
+	if [ "s$STA_SSID" != "s" ];then
+        activateVAP ath$VAP_NUM:$STA_RADIO_ID br0 $STA_SECMODE $STA_SECFILE $WPS_ENABLE
+		VAP_NUM=$(($VAP_NUM+1))
+	if [ -f /tmp/sta_conf_filename ]; then
+            wpa_supplicant `cat /tmp/sta_conf_filename` &
+			sleep 2
+        fi
+    	fi
+	fi
+	
+	if [ "${wds_flag_2}" = "on" ];then	
+	if [ "s$STA_SSID_2" != "s" ];then
+        activateVAP ath$VAP_NUM:$STA_RADIO_ID_2 br0 $STA_SECMODE_2 $STA_SECFILE_2 $WPS_ENABLE_2
+	if [ -f /tmp/sta_conf_filename ]; then
+            wpa_supplicant `cat /tmp/sta_conf_filename` &
+        fi
+    	fi
+	fi
+
     fi
 fi
 
@@ -693,9 +767,11 @@ if [ "${IS_WPA}" != "" -o "${IS_WPS}" != "" ]; then
         if [ -f /tmp/conf_filename ]; then
             hostapd  -B `cat /tmp/conf_filename` -e /etc/wpa2/entropy
         fi
-        if [ -f /tmp/sta_conf_filename ]; then
-            wpa_supplicant `cat /tmp/sta_conf_filename` &
-        fi
+	if [ "${AP_STARTMODE}" != "repeater" ]; then
+        	if [ -f /tmp/sta_conf_filename ]; then
+        	    wpa_supplicant `cat /tmp/sta_conf_filename` &
+		fi
+	fi
     fi
 fi
 
